# Generated by Django 4.0.4 on 2022-05-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('F', 'Fall'), ('SP', 'Spring'), ('SM', 'Summer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.season')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instance', models.IntegerField()),
                ('abbr', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('credits_ects', models.IntegerField()),
                ('credits_us', models.IntegerField()),
                ('breadth', models.CharField(max_length=50)),
                ('ccdisplay', models.BooleanField()),
                ('rno', models.IntegerField()),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.academiclevel')),
                ('antireqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('coreqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.department')),
                ('last_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.semester')),
                ('prereqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.semester')),
            ],
        ),
    ]
