# Generated by Django 4.0.4 on 2022-05-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('instance', models.IntegerField(blank=True, null=True)),
                ('abbr', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('credits_ects', models.DecimalField(decimal_places=4, max_digits=4)),
                ('credits_us', models.DecimalField(decimal_places=4, max_digits=4)),
                ('department', models.CharField(max_length=50)),
                ('breadth', models.CharField(max_length=50)),
                ('ccdisplay', models.BooleanField()),
                ('rno', models.IntegerField()),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.academiclevel')),
                ('antireqs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('coreqs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('last_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.semester')),
                ('prereqs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.semester')),
            ],
        ),
    ]
