# Generated by Django 4.0.4 on 2022-05-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='antireqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course'),
        ),
    ]
