# Generated by Django 4.0.4 on 2022-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits_ects',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits_us',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
