# Generated by Django 4.0.4 on 2022-06-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_course_credits_ects_alter_course_credits_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('instance', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=20)),
                ('times', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=30)),
                ('instructors', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('enrolled', models.IntegerField()),
                ('final_exam', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.course')),
            ],
        ),
    ]
