# Generated by Django 4.0.4 on 2022-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('Lb', 'Lab'), ('PLb', 'PhysLab'), ('BLb', 'BioLab'), ('ChLb', 'ChemLab'), ('CLb', 'CompLab'), ('S', 'Seminar'), ('R', 'Recitation'), ('IS', 'IS'), ('P', 'P'), ('Wsh', 'Wsh'), ('CP', 'CP'), ('Int', 'Internship')], max_length=10),
        ),
    ]
