# Generated by Django 4.0.4 on 2022-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='section',
            name='times',
            field=models.CharField(max_length=30),
        ),
    ]
