# Generated by Django 4.0.4 on 2022-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_section_days_alter_section_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('Lb', 'Lab'), ('PLb', 'PhysLab'), ('BLb', 'BioLab'), ('ChLb', 'ChemLab'), ('CLb', 'CompLab'), ('S', 'Seminar'), ('R', 'Recitation'), ('IS', 'IS'), ('P', 'P'), ('Wsh', 'Wsh'), ('CP', 'CP'), ('Int', 'Internship'), ('ThDef', 'Thesis Defence')], max_length=10),
        ),
    ]
