# Generated by Django 4.0.4 on 2022-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_schedule_chosensection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('Lb', 'Lab'), ('PLb', 'Physics Lab'), ('BLb', 'Biology Lab'), ('ChLb', 'Chemistry Lab'), ('CLb', 'Computer Lab'), ('S', 'Seminar'), ('R', 'Recitation'), ('IS', 'Independent Study'), ('P', 'Project'), ('Wsh', 'Workshop'), ('CP', 'Capstone Project'), ('Int', 'Internship'), ('ThDef', 'Thesis Defence'), ('OCA', 'Occupational Competency Assessment')], max_length=10),
        ),
    ]
